### ISSUE TITLE
Todo: Add tests for the Event Service and Event Controller

### ISSUE THREAD

**Issue by jindalujjwal0720** [we-festify/festify#1]
The Event Service and Event Controller currently lack comprehensive unit tests. To ensure the reliability, stability, and maintainability of our application, it is crucial to create a suite of tests that cover the functionality of these components.

**Comment by cprakash1** [comment]
I will Do it please assign it to me

**Comment by jindalujjwal0720** [comment]
> I'm using sinon as a development dependency to test the controller. Is that okay?
> 

Jest is a pretty decent library for testing and with Jest, supertest works well. If you could contribute to it, it would be better for us.

**Comment by subhashree9898** [comment]
Okay. I will do it accordingly

**Comment by subhashree9898** [comment]
Apologies for the delay. Will raise the pr by tomorrow afternoon.

**Comment by jindalujjwal0720** [comment]
> Apologies for the delay. Will raise the pr by tomorrow afternoon.

That's no problem. Take your time. Learn well and apply well.
After all it's all for learning and growing.

**Comment by Shashankpantiitbhilai** [comment]
i will do it

**Comment by subhashree9898** [comment]
@jindalujjwal0720 I have added the test cases for event controller and raised the PR. Kindly check
