### ISSUE TITLE
Login and Signup page

### ISSUE THREAD

**Issue by doppedheart** [we-festify/festify#20]
Create the login and register page for the Festify web app.

**Requirements**

- simple and elegant (as it is just for viewing, every fest organisation will create its own afterwards)
- should be responsive
- should follow modular CSS and appropriate class names

**Comment by doppedheart** [comment]
working on it 
will finish by tomorrow ?

**Comment by doppedheart** [comment]
can you assign me this issue ?

**Comment by jindalujjwal0720** [comment]
> can you assign me this issue ?

Hi @doppedheart, will open more issues for the required frontend things. You can contribute from now on if you don't mind. This issue was necessary for me to show the setup of frontend in this repository for further use.
