### ISSUE TITLE
Feature: Mailing Utility Service for Templated Emails

### ISSUE THREAD

**Issue by jindalujjwal0720** [we-festify/festify#21]
### Issue Description:

Creating a Mailing Utility Service capable of sending different types of templated emails, such as **Forgot Password** emails and other notification emails, is essential to enhance communication and user experience within our application. This feature will enable us to send well-designed and consistent email templates to users for various purposes.

### Issue Details:

**1. Problem Statement:**

Currently, our application lacks a dedicated Mailing Utility Service for sending templated emails. This leads to a less-than-optimal user experience, especially for essential communication like password reset instructions.

**2. Objectives:**

- Develop a Mailing Utility Service capable of sending templated emails.
- Create email templates for common use cases, such as **Forgot Password**.
- Provide a secure and efficient mechanism for sending emails to users.
- Allow for customization and personalization of email templates.

**3. Benefits:**

- Enhanced communication with users through professionally designed and consistent email templates.
- Improved user experience, especially for critical notifications like password reset instructions.
- Streamlined email sending processes and error handling.
- Capability for future expansion with additional email templates.

**4. Proposed Tasks:**

- Design and develop the Mailing Utility Service to handle email sending.
- Create email templates for common scenarios, such as **Forgot Password**.
- Implement mechanisms for customizing and personalizing email templates with user-specific information.
- Ensure the security and reliability of email transmission.
- Handle error cases, such as bounced emails or delivery failures.
- Test the Mailing Utility Service thoroughly to ensure email delivery functionality.
- Document the usage of the service and email template customization guidelines.

**Comment by github2python** [comment]
Kindly assign this task to me. I want to work on it
