### ISSUE TITLE
Create Events Page inside client web app

### ISSUE THREAD

**Issue by jindalujjwal0720** [we-festify/festify#25]
Create an Events page in the web - apps - client - pages.

**Requirements**

- show all the events
- responsive
- access to anyone without login also
- simple and elegant design
- good and meaningful css class names
- modular and reusable approach to designing components should be followed

**Comment by Rehan52004** [comment]
i want to work on it, please assign to me.

**Comment by Rehan52004** [comment]
I go here -
web --> src --> apps --> client
what i have to do.
please define more about this feature or give me some example or image.

**Comment by jindalujjwal0720** [comment]
> I go here -
> web --> src --> apps --> client
> what i have to do.
> please define more about this feature or give me some example or image.

Have to build an interface where a user can see all the events in a nice fashion. Refer more fest and event management websites for examples.

**Comment by Rehan52004** [comment]
Ok I understand
