### ISSUE TITLE
Forgot Password in Auth

### ISSUE THREAD

**Issue by jindalujjwal0720** [we-festify/festify#33]
Currently there is no way to regain the password if it is lost, for any account. Implement a forgot password feature inside the auth service which should be able to help reset the lost password.

**Todo**
- Implement Reset Password feature in Auth Service
> - Send a mail with a unique link with expiry time to the user's email
> - unique link should be redirected to the web form with a new password and confirm password fields
> - submitting the page should reset the password
> - the link should not be redirected to the web reset password after that

**Comment by github2python** [comment]
Kindly assign it to me, I want to work on it.

**Comment by github2python** [comment]
@jindalujjwal0720 Kindly assign it to me, I want to work on it

**Comment by AnikethDeb2004** [comment]
i want to work on something please anyone help me im an absolute beginner please help meeeeee
