### ISSUE TITLE
Feature : Add Top loader in webpages 

### ISSUE THREAD

**Issue by prashh-k** [we-festify/festify#47]
There should be a Top loader added in each web pages of Website, While when someone refresh or navigates to that page the Top loader should should be visible just like youtube.

In React this is possible through a library called React- top-loader, in which we can add it in our react app.

**Comment by jindalujjwal0720** [comment]
@prashh-k it's a good addition and can be of great use to the app.
But we are a less-dependency environment and try to build things on our own by native scripts.
It would be great if anyone can build this natively using css and react components.
> Make sure to handle the easy usability, less overhead and no breakdowns to existing features.

**Comment by prashh-k** [comment]
ok i will try to do it without effecting other existing features.
