### ISSUE TITLE
Bug: Dropdown displaying behind other elements

### ISSUE THREAD

**Issue by jindalujjwal0720** [we-festify/festify#48]
The current implementation of the dropdown in the application is causing a visual bug where it increases the height of the table, and the dropdown is hidden behind the scrollbars and other elements. This impacts the user experience negatively, making interacting with the dropdown options difficult.

**Expected Behavior:**
The dropdown should appear above the table without affecting its height and be visible and accessible to the user.

**Actual Behavior:**
The dropdown increases the height of the table, and it is partially or fully hidden behind the scrollbars and other elements.

**How would you like to proceed and find?**
You can go to the admin panel or the organiser panel after logging in with respective IDs, and there, you will find the issues with the table and dropdowns.

**Screenshot:**

![Screenshot 2023-11-19 173055](https://github.com/we-festify/festify/assets/43829421/ebd7eedf-7077-420b-87c8-daf8909f3400)

**Comment by JyothsnaVellampalli** [comment]
@jindalujjwal0720 shall I work on this issue.
